### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by aarongerig** [w-vision/ElementManagerBundle#2]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Branch?          | master

If I define a naming scheme an activate it on save, pimcore throws an error.

```yml
# app/config/config.yml

element_manager:
    classes:
    ...
    Event:
        naming_scheme:
            enabled: true
            options:
                parent_path: '/Veranstaltungen'
                archive_path: '/Archiv/Veranstaltungen'
                scheme: '[object.getDate().year, object.getDate().format("m"), object.getName()]'
        ...
```

```log
Validation failed: Empty mandatory field [ name ] / Empty mandatory field [ categories ] / Empty mandatory field [ customer ] (500 Internal Server Error)
```

If I set `enabled` to `false` everything works as expected.
